# -*- coding: utf-8 -*-
"""Copy of think-week4-A108060020-3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Hy1dQdDw_ajmTHvWv93VRg1bRP9vQo8Y
"""

print("Hello World")

print("你好嗎")

print("Hello World")
print("你好嗎")



"""早安

拉拉拉~
"""



"""看的到嗎?"""



"""看得到~yaaaaaaa~"""

